#!/bin/sh

uci set network.lan.ipaddr='10.0.0.8/24'
uci set network.lan.gateway='10.0.0.1'
uci -q delete network.lan.dns
uci add_list network.lan.dns='10.0.0.1'

uci commit network

/etc/init.d/network restart

exit 0
